#define IDENTIFIER	5
#define INTEGER	6
#define ADD_OP	17
#define MUL_OP	30
#define COMP_OP	19
#define OR_OP	41
#define AND_OP	8
#define NOT_OP	7
#define KW_INT	27
#define KW_BOOL	18
#define KW_CONS	20
#define KW_DO	21
#define KW_TAIL	37
#define KW_GOTO	24
#define KW_PREFIX	33
#define KW_INFIX	26
#define KW_POSTFIX	32
#define KW_LEFT	28
#define KW_RIGHT	35
#define KW_NONASSOC	31
#define KW_WITH	40
#define CROC_G	14
#define CROC_D	15
#define PAR_G	9
#define PAR_D	10
#define VIRG	11
#define EGAL	13
#define POINT_VIRG	12
#define DEUX_POINTS	3
#define POINT	16
#define FIRST_PASS	1
#define INT_LHS	48
#define BOOL_LHS	49
#define INT_EXPR	32
#define BOOL_EXPR	50
#define BASIC_TYPE_NAME	13
#define STMT	47
#define INT_CONST	55
#define BOOL_CONST	58
#define INT_FUN	52
#define BOOL_FUN	53
#define INT_VAR	56
#define BOOL_VAR	59
#define INT_PRIMARY	54
#define BOOL_PRIMARY	57
#define LABEL	45
