*********************************************************************
*	 Copyright (c) 2000 by Institut National de Recherche	    *
*		  en Informatique et en Automatique.		    *
*		      Produit de l'equipe ATOLL.		    *
*		      Version 0.1 du 21 mai 2000		    *
*  Syntaxe d'entree pour les mots d'un lexique a traiter par TRICO  *
*********************************************************************

<trico>		= <mots> 			; 1

<mots>		= <mots>
		  %MOT		 		; 2
<mots>		= %MOT 				; 3
