<wcw2-new-start-symbol> = <S> &10000 ;

*
* This is a LIG for the language {wcw | w in {a, b}* }
*

* Error recovery enable since each test is performed while the
* token is parsed (see wcw.lig)

<S> @10001		= <S>&10002 "a"	 	;
<S> @10001		= <S>&10003 "b" 		;
<S> @10000		= <T>&10001		;
*
<T> @10002	= "a" <T>&10001		;
<T> @10003	= "b" <T>&10001		;
<T> @10004		= "c"			;
