********************************************************************
*       Copyright (c) 1987 by Institut National de Recherche       *
*               d'Informatique et d'Automatique.		   *
*          Produit de l'equipe Langages et Traducteurs.    	   *
*                  Version 2.1 du 15 Mai 1987			   *
*	   Syntaxe d'entree pour les definitions de YAX		   *
********************************************************************
<defs>		= ; 12
