*
* This is a LIG for the language {wcw | w in {a, b, c}* }
*

<S>		= <S> "a"	 	;
<S>		= <S> "b" 		;
<S>		= <S> "c" 		;
<S>		= <T>		;
*
<T>	= "a" <T>		;
<T>	= "b" <T>		;
<T>	= "c" <T>		;
<T>		= "c"			;

