#define atom_t	12
#define is_t	11
#define less_t	18
#define less_equal_t	19
#define sup_t	20
#define sup_equal_t	21
#define plus_t	22
#define minus_t	23
#define multiply_t	24
#define divide_t	25
#define modulo_t	26
#define lhs_rhs_sep_t	1
