#! /bin/sh

# Hubert Garavel - August 2023

COMMAND=`basename "$0"`

SX=`dirname "$0"`/../..
ARCH=`$SX/etc/bin/arch`

F77=bin/f77
F77OUT=bin.$ARCH/f77.out

PPF77=bin/ppf77
PPF77OUT=bin.$ARCH/ppf77.out

SPLIT_OPTION=0
VALGRIND_OPTION=0

WD=`pwd`
WD=`basename "$WD"`

while true
do
	case "$1" in
		-split )
			# do not concatenate continuation lines
			SPLIT_OPTION=1
			shift
			;;
		-valgrind )
			# only run valgrind
			VALGRIND_OPTION=1
			shift
			;;
		-* )
			echo "$COMMAND: unknown option $1"
			exit 1
			;;
		* )
			break
	esac
done

#------------------------------------------------------------------------------

if [ $SPLIT_OPTION = 0 ]
then
	SCRIPT=`mktemp`
	cat > $SCRIPT << \EOF
# display comment lines
/^C/ { printf "\n%s", $0 ; next }

# non-continuation line with a zero in column 6: remove the zero
/^[ 0-9][ 0-9][ 0-9][ 0-9][ 0-9]0/ { printf "\n      %s", substr ($0, 7) ; next }

# continuation line without '0' nor ' ' in column 6
/^[ ][ ][ ][ ][ ][^0 ]/ { printf " %s", substr ($0, 7) ; next }

# non-continuation line without a zero in column 6
{ printf "\n%s", $0 }

END {
	printf "\n"
}
EOF
fi

#------------------------------------------------------------------------------

if [ $VALGRIND_OPTION = 1 ]
then
	VALGRIND="valgrind --quiet --track-origins=yes"
	export VALGRIND
fi

#------------------------------------------------------------------------------

FILTER() {
	# remove columns 72-80 of all lines not starting with a "C"
	awk '/^C/ { print ; next } { print substr ($0, 1, 72) }' |
	# remove empty lines
	grep -v '^[ ]*$' |
	# concatenate continuation lines
	if [ $SPLIT_OPTION = 0 ]
	then
		awk -f $SCRIPT -
	else
		cat
	fi
}

#------------------------------------------------------------------------------

RUN() {
	echo ""
	case "$1" in
		-X ) echo "----------- $WD:f77 -X" "$2" | sed -e 's+test/++' ;;
		* )  echo "----------- $WD:f77" "$1" | sed -e 's+test/++' ;;
	esac

	if [ $VALGRIND_OPTION = 1 ]
	then
		echo ""
		# on a positionne la variable globale $VALGRIND
		$F77 $*
		return
	fi

	$F77 $*
	STATUS=$?
	if [ $STATUS != 0 ]
	then
		echo "  exit status is $STATUS"
	fi
}

#------------------------------------------------------------------------------

if [ ! -x $F77OUT -a ! -x $PPF77OUT ]
then
	echo "$COMMAND: no executable f77.out nor ppf77.out found; run sxmake to build them"
	exit 1
fi

#------------------------------------------------------------------------------

RESULT_FILE="error_report.txt"
> "$RESULT_FILE"  

if [ -x $F77OUT ]
then

	for FILE in `ls test/esope/*.E`
	do
		ERR_OUTPUT=$(RUN "$FILE" 2>&1)

    	
    	if [[ -n "$ERR_OUTPUT" ]]; 
    	then
        
        	echo "----------- Errors in: $FILE -----------" >> "$RESULT_FILE"
      	
        	while IFS= read -r line; 
        	do
            	if [[ "$line" =~ ^([^\ ]+),\ line\ ([0-9]+): ]]; 
            	then
                	LINE_NUM=${BASH_REMATCH[2]}  # Extract the line number               
                	echo "$line" >> "$RESULT_FILE"
                	START=$((LINE_NUM - 1))
                	END=$((LINE_NUM + 1))
                	sed -n "${START},${END}p" "$FILE" >> "$RESULT_FILE"
                	echo "" >> "$RESULT_FILE"  # Separate errors with a newline
            	else
                	echo "$line" >> "$RESULT_FILE"
            	fi
        	done <<< "$ERR_OUTPUT"
        
        	echo "" >> "$RESULT_FILE" 
    	fi

	done 
fi

#------------------------------------------------------------------------------

rm -f $SCRIPT $TMP1 $TMP2

exit 0