#!/bin/sh
# Prompt user for a yes/no answer
#
# Copyright (c) 1986 Philippe Deschamp
#
#    Permission is granted to anyone to make or distribute verbatim
#    copies of this document as received, in any medium, provided
#    that the copyright notice and this permission notice are
#    preserved, thus giving the recipient permission to redistribute
#    in turn.
#
#    Permission is granted to distribute modified versions of this
#    document, or of portions of it, under the above conditions,
#    provided also that they carry prominent notices stating who last
#    changed them.

# Last modified by PhD on Fri Mar 11 1988 to not use the "-n" option
# of "echo", which seems to cause problems on some implementations
# of UNIX System V.

USAGE="Usage:	$0 caller_name word ...
or	$0 -doc"
case $1 in
	-doc)echo "$USAGE
Prompts the user with \"word ...\" and expects an answer of \"yes\" (\"y\")
or \"no\" (\"n\"). Any other answer is an error: a message, prefixed by
\"caller_name\", is printed on the terminal, and the user is asked again.
This command exits with code \"0\" if the answer was positive, \"1\" if not."
	     exit;;
esac
case $# in 0) echo "$USAGE">&2;exit 1;;esac
CALLER="$1"
shift
QUESTION="
$* "
ERROR="$CALLER: Please answer \"y\", \"n\", \"yes\" or \"no\""
if test -z "`echo -n`"
   then	N=-n C=''
   else	N='' C='\c'
fi

while :;do
	echo $N "$QUESTION"$C>&2
	if read ANSWER
	then	case $ANSWER in
			y|yes)exit 0;;
			n|no)exit 1;;
			*)echo "$ERROR">/dev/tty;;
		esac;
	else	exit 1;
	fi;
done

# GNU Emacs idiosyncrasies:
# Local Variables:
# version-control: yes
# End:
