<DESAMBIG>		= <OPERATOR_PRIORITY_LIST>
		  	  <RULE_PRIORITY_LIST>			;

<OPERATOR_PRIORITY_LIST>
			= <OPERATOR_PRIORITY_LIST>
		  	  <OPERATOR_PRIORITY>			;
<OPERATOR_PRIORITY_LIST>
			=					;

<OPERATOR_PRIORITY>	= <PRIORITY_KIND> <OPERATOR_LIST>	;

<PRIORITY_KIND>		= "%left"				; 1
<PRIORITY_KIND>		= "%right"				; 2
<PRIORITY_KIND>		= "%nonassoc"				; 3

<OPERATOR_LIST>		= <OPERATOR_LIST> <OPERATOR>		;
<OPERATOR_LIST>		= <OPERATOR>				;

<OPERATOR>		= <X_TERMINAL>				; 4

<RULE_PRIORITY_LIST>	= <RULE_PRIORITY_LIST>
		  	  <RULE_PRIORITY>			;
<RULE_PRIORITY_LIST>	=					; 5

<RULE_PRIORITY>		= <RULE>  ";"  <PRIORITY>		;

<RULE>			= <VOCABULARY_LIST> 			;

<VOCABULARY_LIST>	= <VOCABULARY_LIST>  <VOCABULARY>	;
<VOCABULARY_LIST>	= %LHS_NON_TERMINAL  =	 		; 6

<VOCABULARY>		= <X_NON_TERMINAL> 			; 8
<VOCABULARY>		= <X_TERMINAL>				; 7

<X_NON_TERMINAL>	= %NON_TERMINAL				;
<X_NON_TERMINAL>	= %NON_TERMINAL  %PREDICATE		; 11

<X_TERMINAL>		= <TERMINAL>				;
<X_TERMINAL>		= <TERMINAL>  %PREDICATE		; 10

<TERMINAL>		= %TERMINAL				;
<TERMINAL>		= =					;

<PRIORITY>		= "%prec"  <X_TERMINAL>			; 9
