#! /bin/bash
#
# Nouvelle_version_de_SYNTAX : Création d'une hiérarchie faite de liens symboliques.
#
# Copyright information:
#
# Copyright (c) 1999  Philippe Deschamp <Philippe.Deschamp@INRIA.Fr>
#
#    Permission is granted to anyone to make or distribute verbatim copies
#    of this document as received, in any medium, provided that the
#    copyright notice and this permission notice are preserved,
#    thus giving the recipient permission to redistribute in turn.
#
#    Permission is granted to distribute modified versions
#    of this document, or of portions of it,
#    under the above conditions, provided also that they
#    carry prominent notices stating who last changed them.
#

set -e
sx="$HOME/../common/syntax/5-1b"; cd "$sx"; sx="`pwd`" export sx
xs="$HOME/../common/syntax/6.0"; mkdir "$xs"; cd "$xs"; xs="`pwd`" export xs


cat << PhD
Création du nouveau répertoire partagé de "$xs".
PhD

cd "$xs"
mkdir PARTAGE
cd PARTAGE

"$sx"/taro | (sx="`pwd`" "$sx"/tari)


cat << PhD

Création des divers répertoires système-architecture
PhD
REPS=/tmp/nvds.d$$
find . -noleaf -type d \! -name . -print0 > $REPS
for rep in ../osf1-alpha ../linux-i386 ../solaris-sun4 ../winnt-i386
do
    mkdir "$rep"
    echo "$rep"
    ( cd "$rep" ; xargs --null --no-run-if-empty mkdir ) < $REPS
done
rm $REPS


# GNU Emacs idiosyncrasies:
# Local Variables:
# version-control: yes
# End:
