int i;
bool b;

if 1==1 then;else;

{
listof int l;
listof listof int l2 (listof int);
listof listof listof int l3 [3];

if () == () then;else;

if cons ((), ()) == () then;else;

if cons (i, ()) == () then;else;

if () == cons (i, ()) then;else;

if l2 (l) == cons ((), ()) then;else;

if cons ((), ()) == l2 (l) then;else;

if cons ((), ()) == l3 [1] then;else;

if l == cons ((), ()) then;else;

if cons ((), ()) == l then;else;
}

if cons (b, ()) == () then;else;

if () == cons (b, ()) then;else;

if () == 1 then;else;
