#! /bin/sh
#
# $RCSfile$ : Check-out de SYNTAX depuis son CVS.
#
# Copyright information:
#
# Copyright (c) 2005  Philippe Deschamp <Philippe.Deschamp@INRIA.Fr>
#
#    Permission is granted to anyone to make or distribute verbatim copies
#    of this document as received, in any medium, provided that the
#    copyright notice and this permission notice are preserved,
#    thus giving the recipient permission to redistribute in turn.
#
#    Permission is granted to distribute modified versions
#    of this document, or of portions of it,
#    under the above conditions, provided also that they
#    carry prominent notices stating who last changed them.
#
#@(#) $Id: CVS_checkout_SYNTAX 3390 2023-07-02 08:53:59Z garavel $
 

case "${GNUBIN}" in '') GNUBIN=/usr/local/gnu/bin;;esac

for VAR in find gawk tar xargs
do
    # case "${VAR}" in '')VAR="${GNUBIN}/VAR";test -f "${VAR}" || VAR=VAR;;esac
    eval 'case "${'${VAR}'}" in '\'\'')'${VAR}'="${GNUBIN}/'${VAR}'";test -f "${'${VAR}'}" || '${VAR}'='${VAR}';;esac'
done

case "${CVSROOT}" in '') CVSROOT=`echo '$Source$' | "${gawk}" '{match ($2, ".*/"); print substr ($2, 1, RLENGTH-1);}'`;;esac

case "$0" in */syntax/*) sx=`expr X$0 : 'X\(.*\)/'`;; *) sx=.;;esac
cd "$sx"; sx="`pwd`" export sx
case "$sx" in */syntax) ;; *) sx="$sx"/syntax export sx;;esac

cvs "$@" checkout syntax
ln -s Faire_les_liens_dans_SYNTAX "$sx/Ajouter_des_liens_dans_SYNTAX"
"$sx/Ajouter_des_liens_dans_SYNTAX"


# GNU Emacs idiosyncrasies:
# Local Variables:
# version-control: yes
# End:
