#! /bin/sh
#
# $RCSfile$ : Création d'une hiérarchie faite de liens symboliques.
#
# Copyright information:
#
# Copyright (c) 1999  Philippe Deschamp <Philippe.Deschamp@INRIA.Fr>
#
#    Permission is granted to anyone to make or distribute verbatim copies
#    of this document as received, in any medium, provided that the
#    copyright notice and this permission notice are preserved,
#    thus giving the recipient permission to redistribute in turn.
#
#    Permission is granted to distribute modified versions
#    of this document, or of portions of it,
#    under the above conditions, provided also that they
#    carry prominent notices stating who last changed them.
#
# Mar  1 Fev 2005 : PhD : Utilisation de ${GNUBIN}
# Mer  9 Fev 2005 : PhD : Ajout de Darwin, qqes liens supprimés
#
#@(#) $Id: Faire_les_liens_dans_SYNTAX 3390 2023-07-02 08:53:59Z garavel $
 
# Il FAUT avoir certains binaires GNU

case "${GNUBIN}" in '') GNUBIN=/usr/local/gnu/bin;;esac

for VAR in find gawk tar xargs
do
    # case "${VAR}" in '')VAR="${GNUBIN}/VAR";test -f "${VAR}" || VAR=VAR;;esac
    eval 'case "${'${VAR}'}" in '\'\'')'${VAR}'="${GNUBIN}/'${VAR}'";test -f "${'${VAR}'}" || '${VAR}'='${VAR}';;esac'
done


case "$0" in */*) sx=`expr X$0 : 'X\(.*\)/'`;; *) sx=.;;esac
cd "$sx"; sx="`pwd`" export sx

cat << PhD
Création des divers liens et copie des tables "*_t.c"...
PhD

cd "$sx/PARTAGE"
REPS="/tmp/nvds.d"$$ FICS="/tmp/nvds.f"$$
trap 'rm -rf "$REPS" "$FICS"' 0

"${find}" . -noleaf -type d \! -name . \! -name CVS \! -name .svn -print0 > "$REPS"
("${find}" . -noleaf \( -type d \( -name CVS -o -name .svn \) -prune \) -o \( -type f -print0 \) |
 "${gawk}" -v 'RS=[\0]' -v 'FS='\' -v 'OFS='\'\\\\\'\' '
	{$1=$1}
    /^#|~$|\.(bak|ckp|new|old)$/ {next}
    /_(t|scnr)\.c$|_td\.h$|force-make/	{print "cp -p " FS "../PARTAGE" substr ($0, 2) FS " " FS $0 FS;next}
	{print "ln -s " FS substr (gensub ("[^/]+", "..", "g"), 4) "/PARTAGE" substr ($0, 2) FS " " FS $0 FS "&&echo link " FS $0 FS}
 '
) > "$FICS"

for rep in ../darwin-ppc ../hpux64-ia64 ../irix64-mips ../linux-i386 ../osf1-alpha ../solaris-sun4 ../winnt-i386 ../darwin-i386
do
    echo "$rep"
    mkdir "$rep"
    ( cd "$rep" ; "${xargs}" --null --no-run-if-empty mkdir ) < "$REPS"
    ( cd "$rep" ; sh ) < "$FICS"
done 2>/dev/null


# GNU Emacs idiosyncrasies:
# Local Variables:
# version-control: yes
# End:
