<wcw-new-start-symbol> = <S> ;

************************** 1 **************************
<S>	= <S.1.0.t> ;
<S.1.0.t>	= <S.1.0.b> ;
<S.1.0.b>	= "c" ;
<S.1.0.t>	= <S.t>&10000 ;
<S.b> @10000	= <S.1.0.b> ;
************************** 2 **************************
<S.t> @10001	= <T.2.1> <S.2.2.t>&10002 ;
<T.2.1>	= "a" ;
<S.2.2.t> @10003	= <S.2.2.b>&10003 ;
<S.2.2.b> @10002	= <S.b>&10004 <T.2.2.2> ;
<S.2.2.t> @10005	= <S.t>&10005 ;
<S.b> @10003	= <S.2.2.b>&10003 ;
<T.2.2.2>	= "a" ;
************************** 3 **************************
<S.t> @10001	= <T.3.1> <S.3.2.t>&10006 ;
<T.3.1>	= "b" ;
<S.3.2.t> @10003	= <S.3.2.b>&10003 ;
<S.3.2.b> @10006	= <S.b>&10004 <T.3.2.2> ;
<S.3.2.t> @10007	= <S.t>&10007 ;
<S.b> @10003	= <S.3.2.b>&10003 ;
<T.3.2.2>	= "b" ;
************************** 4 **************************
<S.t> @10001	= <T.4.1> <S.4.2.t>&10008 ;
<T.4.1>	= "c" ;
<S.4.2.t> @10003	= <S.4.2.b>&10003 ;
<S.4.2.b> @10008	= <S.b>&10004 <T.4.2.2> ;
<S.4.2.t> @10009	= <S.t>&10009 ;
<S.b> @10003	= <S.4.2.b>&10003 ;
<T.4.2.2>	= "c" ;
