c      test provided by Pierre Boullier
       SEGMENT, EXEMPL
       LOGICAL         AA, BB(M)
       INTEGER         AA, BB(M)
       REAL            AA, BB(M)
       COMPLEX         AA, BB(M)
       DOUBLEPRECISION AA, BB(M)
       CHARACTER       KK*5, LL(M)*(N)
       IMPLIED         AA, BB(M)
       POINTEUR        OO.P, QQ(M).R
       LOGICAL         SS, TT(N, M)
       END SEGMENT

       end
      

      
