#! /bin/sh

set -e

for FILE in `ls test/*.lus`
do
	BASE=`basename "$FILE" .lus`
	echo "*** testing $BASE.lus"
	./lustre test/$BASE.lus > result.xml
	diff test/xml/$BASE.xml result.xml
	rm -f result.xml
done

