<wcw3-new-start-symbol> = <S> &10000 ;

*
* This is an xLIG for the language {wcw | w in {a, b, c}* }
*

* Error recovery enable since each test is performed while the
* token is parsed (see wcw.lig)

<S> @10001		= <S>&10002 "a"	 	;
<S> @10001		= <S>&10003 "b" 		;
<S> @10001		= <S>&10004 "c" 		;
<S> @10000		= <T>&10001		;
*
<T> @10002	= "a" <T>&10001		;
<T> @10003	= "b" <T>&10001		;
<T> @10004	= "c" <T>&10001		;
<T> @10005		= "c" &0			;
* &0 checks wether the 'c' is in the middle
