*
* Grammaire qui decrit des sources sous forme de simple dag L = (ff? "("  t %SEMLEX? ") )*
*

<AXIOM>		= bodag <SDAG_GRAMMAR> eodag	;

<SDAG_GRAMMAR>	= <SDAG_GRAMMAR> <TOK_SPEC>	;
<SDAG_GRAMMAR>	= ;

<TOK_SPEC>	= <FF> ( <TERMINAL1+> )		; 5

<FF>		= %form				; 2
<FF>		=				; 6

<TERMINAL1+>	= <TERMINAL+>			; 4
<TERMINAL1+>	= <TERMINAL+> %SEMLEX		; 3

<TERMINAL+>	= <TERMINAL1+> <TERMINAL>	;
<TERMINAL+>	= <TERMINAL>			;

<TERMINAL>	= %form				; 1

