#! /bin/sh
# Making the SYNTAX Manual.
#
# Copyright (c) 1988 Philippe Deschamp
#
#    Permission is granted to anyone to make or distribute verbatim
#    copies of this document as received, in any medium, provided
#    that the copyright notice and this permission notice are
#    preserved, thus giving the recipient permission to redistribute
#    in turn.
#
#    Permission is granted to distribute modified versions of this
#    document, or of portions of it, under the above conditions,
#    provided also that they carry prominent notices stating who last
#    changed them.

ME=`basename $0`
WD=`echo $0 | sed  "s+$ME$+.+"`
WD=`cd $WD;pwd`

DOCUMENT=syntax
PRINT=
RUNS=1
while :
do
	case $# in 0) break;;esac
	case "$1" in
	nonce)	RUNS=;;
	once)	RUNS=1;;
	twice)	RUNS="1 2";;
	lw)	PRINT=lw	DOPRINT='lpr -d -PPostScript';;
	p400)	PRINT=p400	DOPRINT='dvi2agfa';;
	syntax|title)
		DOCUMENT=$1;;
	*)	echo "Usage: $ME [([n]on|twi)ce] [lw|p400] [syntax|title]" >&2
		exit 1;;
	esac
	shift
done
set -e
cd /tmp

/bin/cp $WD/$DOCUMENT.ftex $DOCUMENT.ftex
for RUN in $RUNS
do
	/bin/rm -f $DOCUMENT.dvi
	makelatex $DOCUMENT.dvi
done

case $PRINT in
    lw)
    	$DOPRINT $DOCUMENT.dvi;;
    p400)
    	$DOPRINT $DOCUMENT.dvi;;
esac
