********************************************************************
*       Copyright (c) 1987 by Institut National de Recherche       *
*               d'Informatique et d'Automatique.		   *
*          Produit de l'equipe Langages et Traducteurs.    	   *
*                  Version 0.1 du 1er Septembre 1987		   *
*	   Syntaxe d'entree pour les actions en YSX		   *
********************************************************************
<action>	= ; 0
