#!/bin/sh

# On positionne des variables pour rendre malloc() et free() plus stricts
# (voir page man de malloc sous macOS)

MallocScribble=1
export MallocScribble

MallocPreScribble=1
export MallocPreScribble

MallocGuardEdges=1
export MallocGuardEdges

MallocStackLogging=1
export MallocStackLogging

MallocCheckHeapEach=1000
export MallocCheckHeapEach

MallocCheckHeapStart=1000
export MallocCheckHeapStart

MallocGuardEdges=1
export MallocGuardEdges

# creation d'un fichier contenant les messages emis par malloc() et free()

MallocLogFile=$SX/_scribble.log
export MallocLogFile 

