#define void_la	57
#define char_la	58
#define int_la	59
#define float_la	60
#define double_la	61
#define struct_la	64
#define union_la	65
#define enum_la	67
#define short_la	55
#define long_la	56
#define signed_la	53
#define unsigned_la	54
#define extern_la	49
#define static_la	50
#define auto_la	51
#define register_la	52
#define const_la	68
#define volatile_la	69
#define typedef_la	48
#define oper_and_la	14
#define oper_mult_la	15
#define oper_plus_la	16
#define oper_minus_la	17
#define oper_tilde_la	18
#define oper_not_la	19
