#! /bin/sh
# INSTALLation of a production version of SYNTAX.
#
# Copyright (c) 1985 Philippe Deschamp
#
#    Permission is granted to anyone to make or distribute verbatim
#    copies of this document as received, in any medium, provided
#    that the copyright notice and this permission notice are
#    preserved, thus giving the recipient permission to redistribute
#    in turn.
#
#    Permission is granted to distribute modified versions of this
#    document, or of portions of it, under the above conditions,
#    provided also that they carry prominent notices stating who last
#    changed them.

# Last modified by PhD on Wed Mar 16 1988 to not use the "-n" option
# of "echo", which seems to cause problems on some implementations
# of UNIX System V.

B=`basename $0`
SOURCE=`echo $0 | sed  "s+$B$+.+"`
SOURCE=`cd $SOURCE;pwd`
if test -z "$DEST"
   then DEST=/usr/local/
fi
if test ! -d "$DEST"
   then echo 'The variable "DEST" must be set to the name of a DIRECTORY!'>&2
	exit 1
fi
DEST=`cd $DEST;pwd`
case $DEST in
    */) ;;
    *)	DEST=$DEST/;;
esac

ko=1
trap 'rm -fr /tmp/$$;exit' 1 2 
(
if test -z "`echo -n`"
   then	N=-n C=''
   else	N='' C='\c'
fi

cd $SOURCE
mkdir /tmp/$$
ls -d [a-z]* | sed "/lost+found/d" > /tmp/$$/1
LISTE=`cat /tmp/$$/1`
echo
echo $N "VOULEZ-VOUS VERIFIER VOTRE ESPACE DISQUE?: "$C
read R
case $R in
y*|Y*|o*|O*)
	> /tmp/$$/$$
	if test "$@"
	   then	LI="$@ STOP"
	fi
	while test "$LISTE"
	do
	set -$- ""$LI
	if test "$1"
	   then i=$1; shift; LI="$@"
	   else echo 'Choisissez parmi:'
		echo $N "$LISTE ou STOP: "$C
		read i
	fi
	case $i in
	STOP)break;;
	*)
	L=$LISTE; 
	if grep "^$i"'$' /tmp/$$/1 >/dev/null 2>&1
	   then sed  '/^'"$i"'$/d' /tmp/$$/1 > /tmp/$$/2
		mv /tmp/$$/2 /tmp/$$/1
		LISTE=`cat /tmp/$$/1`
	   else echo $i inconnu>&2
		continue
	fi
	echo Verification si place suffisante pour installer $i
	cp /tmp/$$/$$ /tmp/$$/$i
	set -$- `cat $i/SIZE`
	while test $1
	do
	P=$1
	while : ;
	do
		DEV=""`df $DEST$P/ 2>/dev/null | fgrep -v system | fgrep -v 'Mounted on'`
		if test "$DEV"
		   then break
		fi
		P=`echo $P | sed 's+[^/]*$++
				  s+/$++'`
		if test -z "$P"
		   then echo "Impossible de trouver la place disponible pour $1...">&2
			echo "Veuillez avorter l'execution et recommencer.">&2
			sleep 60
			exit 1
		fi
	done
	if test `echo $DEV | fgrep -c block` = 1
	   then	# ~SPIX?
		PL=`echo $DEV | sed -e 's/^.*\:[ \t]*//
					s/block.*//'`
	   else	# ~SUN?
		PL=`set -$- $DEV;echo $4`
	fi
	DEV=`IFS="$IFS/(";set -$- $DEV;echo $2`
	LINE=`grep $DEV /tmp/$$/$i`; VAL=$2
	if test "$LINE"
	   then	VAL=`set -$- $LINE; expr $2 + $VAL`
		sed -e "s/$DEV .*/$DEV $VAL/" /tmp/$$/$i > /tmp/$$/$i.X
		mv /tmp/$$/$i.X /tmp/$$/$i
	   else echo "$DEV $2" >> /tmp/$$/$i; VAL=$2
	fi
	if test $PL -lt $VAL
	   then	echo Place insuffisante sous ${DEST}$P:>&2
		echo "	-il y a $PL blocs libres; il en faut $VAL ">&2
		ko=0
	fi
	shift; shift
	done
	if test $ko -eq 0
	   then	ko=1
		rm /tmp/$$/$i
	   else mv /tmp/$$/$i /tmp/$$/$$
		ok="$ok $i"
		echo ok
	fi
	;;
	esac
done
	rm /tmp/$$/$$ ;;
*)	if test  "$@"
	   then while test "$1"
		do
			if test -d "$1"
			   then ok="$ok $1"
			   else echo $1 inconnu>&2
			fi
			shift
			done
	   else ok=$LISTE
	fi;;
esac

if test "$ok"
   then echo
	echo "INSTALLATION sur $DEST"
	for i in $ok
	do
		echo $N "On copie  $i ?: "$C; read R
		case $R in
		y*|Y*|o*|O*) (cd $DEST; cpio -imd < $SOURCE/$i/$i);;
		*) continue;;
		esac 
	done
fi
rm -fr /tmp/$$
)
